import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalStyles } from './globalStyles'
import Header from '@/components/Header'
import StyledComponentsRegistry from '@/libs/registry'


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <GlobalStyles />
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>

    </html>
  )
}
